import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body
          className={`${inter.className} antialiased`}
        >
          <div className="min-h-screen lg:grid lg:grid-cols-(--default) dark:bg-zinc-900">
            <Sidebar />
            <main className="px-4 pb-12 pt-24 lg:col-start-2 my-10 lg:m-0 lg:px-8 lg:pt-8 max-w-screen">
              {children}
            </main>          
          </div>
        </body>
     
    </html>
  );
}
